<?php

declare(strict_types=1);

// GENERATED by cargo xtask gen-host-facts. Do not edit by hand.

namespace Phalanx\Bia\Runtime\Host;

enum AppEnv: string
{
    case Dev = 'dev';
    case Test = 'test';
    case Prod = 'prod';
}
