<?php

declare(strict_types=1);

// GENERATED by cargo xtask gen-host-facts. Do not edit by hand.

namespace Phalanx\Bia\Runtime\Host;

use InvalidArgumentException;

final class BiaFacts
{
    public function __construct(
        private(set) ?int $timeoutMs,
        private(set) ?int $concurrency,
        private(set) bool $verbose,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function hydrate(array $data): self
    {
        self::assertShape($data, ['timeout_ms', 'concurrency', 'verbose'], 'BiaFacts');
        $timeout = $data['timeout_ms'];
        $concurrency = $data['concurrency'];
        if ($timeout !== null && !is_int($timeout)) { throw new InvalidArgumentException('BiaFacts.timeout_ms must be int|null.'); }
        if ($concurrency !== null && !is_int($concurrency)) { throw new InvalidArgumentException('BiaFacts.concurrency must be int|null.'); }
        if (!is_bool($data['verbose'])) { throw new InvalidArgumentException('BiaFacts.verbose must be bool.'); }
        return new self($timeout, $concurrency, $data['verbose']);
    }

    /** @return array{timeout_ms: ?int, concurrency: ?int, verbose: bool} */
    public function toArray(): array
    {
        return ['timeout_ms' => $this->timeoutMs, 'concurrency' => $this->concurrency, 'verbose' => $this->verbose];
    }

    /** @param array<string, mixed> $data @param list<string> $keys */
    private static function assertShape(array $data, array $keys, string $type): void
    {
        $actual = array_keys($data);
        $missing = array_values(array_diff($keys, $actual));
        $unknown = array_values(array_diff($actual, $keys));

        if ($missing !== []) {
            throw new InvalidArgumentException($type . ' missing keys: ' . implode(', ', $missing));
        }

        if ($unknown !== []) {
            throw new InvalidArgumentException($type . ' unknown keys: ' . implode(', ', $unknown));
        }
    }

}
