<?php

declare(strict_types=1);

// GENERATED by cargo xtask gen-host-facts. Do not edit by hand.

namespace Phalanx\Bia\Runtime\Host;

use InvalidArgumentException;
use RuntimeException;

final class HostFacts
{
    public const int CONTRACT = 1;

    /** @param list<string> $argv */
    public function __construct(
        private(set) int $contract,
        private(set) bool $embedded,
        private(set) array $argv,
        private(set) AppEnv $appEnv,
        private(set) PhpFacts $php,
        private(set) SwooleFacts $swoole,
        private(set) ?ServeFacts $serve,
        private(set) BiaFacts $bia,
        private(set) PathFacts $paths,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function hydrate(array $data): self
    {
        self::assertShape($data, ['contract', 'embedded', 'argv', 'app_env', 'php', 'swoole', 'serve', 'bia', 'paths'], 'HostFacts');
        if (!is_int($data['contract'])) { throw new InvalidArgumentException('HostFacts.contract must be int.'); }
        if ($data['contract'] !== self::CONTRACT) {
            throw new RuntimeException("handoff contract mismatch: host speaks v{$data['contract']}, runtime expects v" . self::CONTRACT . "\n-> upgrade bia or pin phalanx-php/phalanx");
        }
        if (!is_bool($data['embedded'])) { throw new InvalidArgumentException('HostFacts.embedded must be bool.'); }
        $argv = self::listOfString($data['argv'], 'HostFacts.argv');
        $appEnv = is_string($data['app_env']) ? AppEnv::from($data['app_env']) : throw new InvalidArgumentException('HostFacts.app_env must be string.');
        $php = is_array($data['php']) ? PhpFacts::hydrate($data['php']) : throw new InvalidArgumentException('HostFacts.php must be object.');
        $swoole = is_array($data['swoole']) ? SwooleFacts::hydrate($data['swoole']) : throw new InvalidArgumentException('HostFacts.swoole must be object.');
        $serve = $data['serve'] === null ? null : (is_array($data['serve']) ? ServeFacts::hydrate($data['serve']) : throw new InvalidArgumentException('HostFacts.serve must be object|null.'));
        $bia = is_array($data['bia']) ? BiaFacts::hydrate($data['bia']) : throw new InvalidArgumentException('HostFacts.bia must be object.');
        $paths = is_array($data['paths']) ? PathFacts::hydrate($data['paths']) : throw new InvalidArgumentException('HostFacts.paths must be object.');
        return new self($data['contract'], $data['embedded'], $argv, $appEnv, $php, $swoole, $serve, $bia, $paths);
    }

    /** @return array<string, mixed> */
    public function toArray(): array
    {
        return [
            'contract' => $this->contract,
            'embedded' => $this->embedded,
            'argv' => $this->argv,
            'app_env' => $this->appEnv->value,
            'php' => $this->php->toArray(),
            'swoole' => $this->swoole->toArray(),
            'serve' => $this->serve?->toArray(),
            'bia' => $this->bia->toArray(),
            'paths' => $this->paths->toArray(),
        ];
    }

    /** @return list<string> */
    private static function listOfString(mixed $value, string $path): array
    {
        if (!is_array($value) || array_is_list($value) === false) {
            throw new InvalidArgumentException("{$path} must be list<string>.");
        }

        foreach ($value as $item) {
            if (!is_string($item)) {
                throw new InvalidArgumentException("{$path} must be list<string>.");
            }
        }

        return $value;
    }

    /** @param array<string, mixed> $data @param list<string> $keys */
    private static function assertShape(array $data, array $keys, string $type): void
    {
        $actual = array_keys($data);
        $missing = array_values(array_diff($keys, $actual));
        $unknown = array_values(array_diff($actual, $keys));

        if ($missing !== []) {
            throw new InvalidArgumentException($type . ' missing keys: ' . implode(', ', $missing));
        }

        if ($unknown !== []) {
            throw new InvalidArgumentException($type . ' unknown keys: ' . implode(', ', $unknown));
        }
    }

}
