<?php

declare(strict_types=1);

// GENERATED by cargo xtask gen-host-facts. Do not edit by hand.

namespace Phalanx\Bia\Runtime\Host;

use InvalidArgumentException;

final class PathFacts
{
    /** @param list<string> $watch */
    public function __construct(
        private(set) string $runtimeDir,
        private(set) string $cwd,
        private(set) array $watch,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function hydrate(array $data): self
    {
        self::assertShape($data, ['runtime_dir', 'cwd', 'watch'], 'PathFacts');
        if (!is_string($data['runtime_dir'])) { throw new InvalidArgumentException('PathFacts.runtime_dir must be string.'); }
        if (!is_string($data['cwd'])) { throw new InvalidArgumentException('PathFacts.cwd must be string.'); }
        return new self($data['runtime_dir'], $data['cwd'], self::listOfString($data['watch'], 'PathFacts.watch'));
    }

    /** @return array{runtime_dir: string, cwd: string, watch: list<string>} */
    public function toArray(): array
    {
        return ['runtime_dir' => $this->runtimeDir, 'cwd' => $this->cwd, 'watch' => $this->watch];
    }

    /** @return list<string> */
    private static function listOfString(mixed $value, string $path): array
    {
        if (!is_array($value) || array_is_list($value) === false) {
            throw new InvalidArgumentException("{$path} must be list<string>.");
        }

        foreach ($value as $item) {
            if (!is_string($item)) {
                throw new InvalidArgumentException("{$path} must be list<string>.");
            }
        }

        return $value;
    }

    /** @param array<string, mixed> $data @param list<string> $keys */
    private static function assertShape(array $data, array $keys, string $type): void
    {
        $actual = array_keys($data);
        $missing = array_values(array_diff($keys, $actual));
        $unknown = array_values(array_diff($actual, $keys));

        if ($missing !== []) {
            throw new InvalidArgumentException($type . ' missing keys: ' . implode(', ', $missing));
        }

        if ($unknown !== []) {
            throw new InvalidArgumentException($type . ' unknown keys: ' . implode(', ', $unknown));
        }
    }

}
