<?php

declare(strict_types=1);

// GENERATED by cargo xtask gen-host-facts. Do not edit by hand.

namespace Phalanx\Bia\Runtime\Host;

use InvalidArgumentException;

final class PhpFacts
{
    /** @param array<string, string> $ini */
    public function __construct(
        private(set) string $memoryLimit,
        private(set) array $ini,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function hydrate(array $data): self
    {
        self::assertShape($data, ['memory_limit', 'ini'], 'PhpFacts');
        if (!is_string($data['memory_limit'])) { throw new InvalidArgumentException('PhpFacts.memory_limit must be string.'); }
        if (!is_array($data['ini'])) { throw new InvalidArgumentException('PhpFacts.ini must be object.'); }
        $ini = [];
        foreach ($data['ini'] as $key => $value) {
            if (!is_string($key) || !is_string($value)) { throw new InvalidArgumentException('PhpFacts.ini must be array<string, string>.'); }
            $ini[$key] = $value;
        }
        return new self($data['memory_limit'], $ini);
    }

    /** @return array{memory_limit: string, ini: array<string, string>} */
    public function toArray(): array
    {
        return ['memory_limit' => $this->memoryLimit, 'ini' => $this->ini];
    }

    /** @param array<string, mixed> $data @param list<string> $keys */
    private static function assertShape(array $data, array $keys, string $type): void
    {
        $actual = array_keys($data);
        $missing = array_values(array_diff($keys, $actual));
        $unknown = array_values(array_diff($actual, $keys));

        if ($missing !== []) {
            throw new InvalidArgumentException($type . ' missing keys: ' . implode(', ', $missing));
        }

        if ($unknown !== []) {
            throw new InvalidArgumentException($type . ' unknown keys: ' . implode(', ', $unknown));
        }
    }

}
