<?php

declare(strict_types=1);

// GENERATED by cargo xtask gen-host-facts. Do not edit by hand.

namespace Phalanx\Bia\Runtime\Host;

use InvalidArgumentException;

final class ServeFacts
{
    public function __construct(
        private(set) string $listen,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function hydrate(array $data): self
    {
        self::assertShape($data, ['listen'], 'ServeFacts');
        if (!is_string($data['listen'])) { throw new InvalidArgumentException('ServeFacts.listen must be string.'); }
        return new self($data['listen']);
    }

    /** @return array{listen: string} */
    public function toArray(): array
    {
        return ['listen' => $this->listen];
    }

    /** @param array<string, mixed> $data @param list<string> $keys */
    private static function assertShape(array $data, array $keys, string $type): void
    {
        $actual = array_keys($data);
        $missing = array_values(array_diff($keys, $actual));
        $unknown = array_values(array_diff($actual, $keys));

        if ($missing !== []) {
            throw new InvalidArgumentException($type . ' missing keys: ' . implode(', ', $missing));
        }

        if ($unknown !== []) {
            throw new InvalidArgumentException($type . ' unknown keys: ' . implode(', ', $unknown));
        }
    }

}
