<?php

declare(strict_types=1);

// GENERATED by cargo xtask gen-host-facts. Do not edit by hand.

namespace Phalanx\Bia\Runtime\Host;

use InvalidArgumentException;

final class SwooleFacts
{
    /** @param list<string> $hooks */
    public function __construct(
        private(set) int $eventWorkers,
        private(set) int $taskWorkers,
        private(set) array $hooks,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function hydrate(array $data): self
    {
        self::assertShape($data, ['event_workers', 'task_workers', 'hooks'], 'SwooleFacts');
        if (!is_int($data['event_workers'])) { throw new InvalidArgumentException('SwooleFacts.event_workers must be int.'); }
        if (!is_int($data['task_workers'])) { throw new InvalidArgumentException('SwooleFacts.task_workers must be int.'); }
        return new self($data['event_workers'], $data['task_workers'], self::listOfString($data['hooks'], 'SwooleFacts.hooks'));
    }

    /** @return array{event_workers: int, task_workers: int, hooks: list<string>} */
    public function toArray(): array
    {
        return ['event_workers' => $this->eventWorkers, 'task_workers' => $this->taskWorkers, 'hooks' => $this->hooks];
    }

    /** @return list<string> */
    private static function listOfString(mixed $value, string $path): array
    {
        if (!is_array($value) || array_is_list($value) === false) {
            throw new InvalidArgumentException("{$path} must be list<string>.");
        }

        foreach ($value as $item) {
            if (!is_string($item)) {
                throw new InvalidArgumentException("{$path} must be list<string>.");
            }
        }

        return $value;
    }

    /** @param array<string, mixed> $data @param list<string> $keys */
    private static function assertShape(array $data, array $keys, string $type): void
    {
        $actual = array_keys($data);
        $missing = array_values(array_diff($keys, $actual));
        $unknown = array_values(array_diff($actual, $keys));

        if ($missing !== []) {
            throw new InvalidArgumentException($type . ' missing keys: ' . implode(', ', $missing));
        }

        if ($unknown !== []) {
            throw new InvalidArgumentException($type . ' unknown keys: ' . implode(', ', $unknown));
        }
    }

}
